/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jinrong_zaxiang_callcpp_CppFunc */

#ifndef _Included_com_jinrong_zaxiang_callcpp_CppFunc
#define _Included_com_jinrong_zaxiang_callcpp_CppFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jinrong_zaxiang_callcpp_CppFunc
 * Method:    getList
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_jinrong_zaxiang_callcpp_CppFunc_getList
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
